version: '3.4'

services:
  onboardingapi:
    image: ${DOCKER_REGISTRY-}onboardingapi
    build:
      context: .
      dockerfile: OnboardingAPI/Dockerfile

  interviewapi:
    image: ${DOCKER_REGISTRY-}interviewapi
    build:
      context: .
      dockerfile: InterviewAPI/Dockerfile


  authenticationapi:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: AuthethicationAPI/Dockerfile


  recruitngapi:
    image: ${DOCKER_REGISTRY-}recruitngapi
    build:
      context: .
      dockerfile: RecruitngAPI/Dockerfile

