// <auto-generated />
using System;
using InterviewInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewInfrastructure.Migrations
{
    [DbContext(typeof(InterViewDbContext))]
    [Migration("20230424204239_fix foreignkey issues attempt")]
    partial class fixforeignkeyissuesattempt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InterviewCore.Entity.Interview", b =>
                {
                    b.Property<int>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewId"), 1L, 1);

                    b.Property<int>("InterviewFeedBackId")
                        .HasColumnType("int");

                    b.Property<int>("InterviewRound")
                        .HasColumnType("int");

                    b.Property<int>("InterviewTypeCode")
                        .HasColumnType("int");

                    b.Property<int>("InterviewerId")
                        .HasColumnType("int");

                    b.Property<int>("RecruiterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduleOn")
                        .HasColumnType("datetime2");

                    b.HasKey("InterviewId");

                    b.HasIndex("InterviewFeedBackId");

                    b.HasIndex("InterviewTypeCode");

                    b.HasIndex("InterviewerId");

                    b.HasIndex("RecruiterID");

                    b.ToTable("Interview");
                });

            modelBuilder.Entity("InterviewCore.Entity.Interviewer", b =>
                {
                    b.Property<int>("InterviewerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewerID"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FistName")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("InterviewerID");

                    b.ToTable("Interviewer");
                });

            modelBuilder.Entity("InterviewCore.Entity.InterviewFeedBack", b =>
                {
                    b.Property<int>("InterviewFeedBackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewFeedBackId"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("InterviewFeedBackId");

                    b.ToTable("InterviewFeedBack");
                });

            modelBuilder.Entity("InterviewCore.Entity.InterviewType", b =>
                {
                    b.Property<int>("InterviewTypeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewTypeCode"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("InterviewTypeCode");

                    b.ToTable("interviewTypes");
                });

            modelBuilder.Entity("InterviewCore.Entity.Recruiter", b =>
                {
                    b.Property<int>("RecruiterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecruiterId"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FistName")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("RecruiterId");

                    b.ToTable("Recruiter");
                });

            modelBuilder.Entity("InterviewCore.Entity.Interview", b =>
                {
                    b.HasOne("InterviewCore.Entity.InterviewFeedBack", "InterviewFeedBack")
                        .WithMany("Interview")
                        .HasForeignKey("InterviewFeedBackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewCore.Entity.InterviewType", "InterviewType")
                        .WithMany("Interview")
                        .HasForeignKey("InterviewTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewCore.Entity.Interviewer", "Interviewer")
                        .WithMany("Interview")
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewCore.Entity.Recruiter", "Recruiter")
                        .WithMany("Interview")
                        .HasForeignKey("RecruiterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewFeedBack");

                    b.Navigation("InterviewType");

                    b.Navigation("Interviewer");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("InterviewCore.Entity.Interviewer", b =>
                {
                    b.Navigation("Interview");
                });

            modelBuilder.Entity("InterviewCore.Entity.InterviewFeedBack", b =>
                {
                    b.Navigation("Interview");
                });

            modelBuilder.Entity("InterviewCore.Entity.InterviewType", b =>
                {
                    b.Navigation("Interview");
                });

            modelBuilder.Entity("InterviewCore.Entity.Recruiter", b =>
                {
                    b.Navigation("Interview");
                });
#pragma warning restore 612, 618
        }
    }
}
